<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.0" />
        <PackageReference Include="Dunet" Version="1.11.2"/>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="4.14.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.14.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
        <PackageReference Include="OneOf" Version="3.0.271"/>
        <PackageReference Include="OneOf.SourceGenerator" Version="3.0.271"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\AterraEngine.Unions.Generators\AterraEngine.Unions.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\..\src\AterraEngine.Unions\AterraEngine.Unions.csproj"/>


        <!-- Ugly, but this is because of some weirdness with how analyzers are imported through a project reference -->
        <!-- Yes this is the same thing we have to do in the example, else it fails to load the benchmark -->
        <PackageReference Include="CodeOfChaos.GeneratorTools" Version="1.11.0" GeneratePathProperty="true" PrivateAssets="all" />
        <Analyzer Include="$(PkgCodeOfChaos_GeneratorTools)\lib\netstandard2.0\*.dll" />
    </ItemGroup>

</Project>
