<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AterraEngine.Unions.Generators\AterraEngine.Unions.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\AterraEngine.Unions.Lib\AterraEngine.Unions.Lib.csproj" />

        <!-- Ugly, but this is because of some weirdness with how analyzers are imported through a project reference -->
        <PackageReference Include="CodeOfChaos.GeneratorTools" Version="1.4.1" GeneratePathProperty="true" PrivateAssets="all" />
        <Analyzer Include="$(PkgCodeOfChaos_GeneratorTools)\lib\netstandard2.0\*.dll" />
        <ProjectReference Include="..\AterraEngine.Unions\AterraEngine.Unions.csproj" />
    </ItemGroup>
</Project>
