<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2024.3.0"/>
        <PackageReference Include="TUnit" Version="0.12.14" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\AterraEngine.Unions.Lib\AterraEngine.Unions.Lib.csproj" />
        <ProjectReference Include="..\..\src\AterraEngine.Unions\AterraEngine.Unions.csproj"/>
    </ItemGroup>

</Project>
