<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net9.0;net8.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>

        <IsPackable>true</IsPackable>
        <PackageId>AterraEngine.Unions</PackageId> <!-- Main package name -->
        <Version>6.1.0</Version> <!-- Package version -->
        <Authors>Anna Sas</Authors>
        <Description>A small package allowing you to use Union Structs</Description>
        <PackageProjectUrl>https://github.com/AterraEngine/unions-cs/</PackageProjectUrl>
        <PackageTags>discriminated unions</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <IncludeSymbols>true</IncludeSymbols>
        <DebugType>embedded</DebugType>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
    </PropertyGroup>


    <ItemGroup>
        <None Include="../../LICENSE" Pack="true" PackagePath="" Visible="false" />
        <None Include="../../README.md" Pack="true" PackagePath="" />
        <None Include="../../assets/icon.png" Pack="true" PackagePath="" Visible="false" />
    </ItemGroup>

    <ItemGroup>
        <!-- ProjectReference for the generator as an analyzer -->
        <PackageReference Include="IsExternalInit" Version="1.0.3">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Nullable" Version="1.3.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <ProjectReference Include="..\AterraEngine.Unions.Generators\AterraEngine.Unions.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
